/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package workdata.view;

import javax.swing.JFrame;

/**
 *
 * @author Walt's
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        areadetrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        Cadastro_Produto = new javax.swing.JMenuItem();
        Cadastro_Usuario = new javax.swing.JMenuItem();
        Cadastro_Ordem = new javax.swing.JMenuItem();
        Bsair = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout areadetrabalhoLayout = new javax.swing.GroupLayout(areadetrabalho);
        areadetrabalho.setLayout(areadetrabalhoLayout);
        areadetrabalhoLayout.setHorizontalGroup(
            areadetrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        areadetrabalhoLayout.setVerticalGroup(
            areadetrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(63, 23));

        jMenu2.setText("Cadastrar");

        Cadastro_Produto.setText("Produto");
        Cadastro_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_ProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Produto);

        Cadastro_Usuario.setText("Usuario");
        Cadastro_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_UsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Usuario);

        Cadastro_Ordem.setText("Ordem de Produção");
        Cadastro_Ordem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_OrdemActionPerformed(evt);
            }
        });
        jMenu2.add(Cadastro_Ordem);

        jMenuBar1.add(jMenu2);

        Bsair.setText("Sair");
        Bsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsairActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Bsair.add(jMenuItem1);

        jMenuBar1.add(Bsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areadetrabalho)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areadetrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_UsuarioActionPerformed
        Cadastro_usuario cadastro = new Cadastro_usuario();
        areadetrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setTitle("Cadastro de Usuario");
        cadastro.setLocation(this.getWidth()/2-cadastro.getWidth()/2,
                             this.getHeight()/2-cadastro.getHeight()/2);
    }//GEN-LAST:event_Cadastro_UsuarioActionPerformed

    private void Cadastro_OrdemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_OrdemActionPerformed
        Cadastro_ordem cadastro = new Cadastro_ordem();
        areadetrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setTitle("Cadastro de Ordem de Produção");
        cadastro.setLocation(this.getWidth()/2-cadastro.getWidth()/2,
                             this.getHeight()/2-cadastro.getHeight()/2);
    }//GEN-LAST:event_Cadastro_OrdemActionPerformed

    private void BsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BsairActionPerformed

    private void Cadastro_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_ProdutoActionPerformed
        Cadastro_produto cadastro = new Cadastro_produto();
        areadetrabalho.add(cadastro);
        cadastro.setVisible(true);
        cadastro.setTitle("Cadastro de Produto");
        //cadastro.setSize(this.getWidth(),this.getHeight());
        cadastro.setLocation(this.getWidth()/2-cadastro.getWidth()/2,
                             this.getHeight()/2-cadastro.getHeight()/2);
    }//GEN-LAST:event_Cadastro_ProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Bsair;
    private javax.swing.JMenuItem Cadastro_Ordem;
    private javax.swing.JMenuItem Cadastro_Produto;
    private javax.swing.JMenuItem Cadastro_Usuario;
    private javax.swing.JDesktopPane areadetrabalho;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
